name: GitHub-Pages-CD-CI
on: push
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out Code
        uses: actions/checkout@v3
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install dependencies
        run: npm install
      - name: build sources
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
  # Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PANOPTICON_CD_CI }}
          publish_dir: ./dist
